#!/usr/bin/env bash

set -Ceu

if [ -z "$TMUX" ]; then
  exit 1
fi

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
selected_session="$(tmux list-sessions -F \#S | fzf-tmux -d 30 --preview="${SCRIPTS_DIR}/show_session_tree {} {q}" | cut -d : -f 1)"
if [ -n "$selected_session" ]; then
  tmux switch -t $selected_session
fi
