#!/usr/bin/env bash

set -Ceu

if [ -z "$TMUX" ]; then
  tmux display-message "Failed to start fzf_tmux_session: tmux process is not running."
  exit 0
fi

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
selected_session="$(tmux list-sessions -F \#S | fzf-tmux -d 30 --preview="${SCRIPTS_DIR}/show_session_tree {} {q}")"
if [ -n "$selected_session" ]; then
  tmux switch -t $selected_session
fi
