#!/bin/bash

set -Ceu

[ -n "$1" ] && selected_session=`echo $1 | sed s/:.*//` || selected_session=''
[ -n "$2" ] && candidate_sessions=`tmux ls -F\#S | fzf -f $2` || candidate_sessions=''

echo_session_name() {
  local session=$1

  if [ "$selected_session" = "$session" ]; then
    echo -e "\033[31m$session (selected)\033[0m"
  else
    echo -e "\033[1m$session\033[0m"
  fi
}

echo_window_in_session() {
  local session=$1

  tmux lsw -t "$session" | while read -r window; do
    window_info=$(echo "$window" | sed -e "s/\[.*//")
    echo "  ﬌ ${window_info}"
  done
}

echo_session_tree() {
  local sessions=$1

  for session in ${sessions[@]}; do
    echo_session_name $session
    echo_window_in_session "$session"
  done
}

if [ "$candidate_sessions" = '' ]; then
  echo_session_tree "`tmux ls -F\#S`"
else
  echo_session_tree "$candidate_sessions"
fi
